apiVersion: v2
name: helm-apps
description: A Helm applications library
type: library
version: 1.7.1
icon: https://raw.githubusercontent.com/alvnukov/helm-apps/main/docs/assets/icon.png
maintainers:
  - name: alvnukov
    url: https://github.com/alvnukov
